### ISSUE TITLE
Panic when selecting an altered UDT

### ISSUE THREAD

**Issue by dfaust** [AlexPikalov/cdrs#190] opened 2017-12-11 22:21 UTC
After adding new fields to a UDT I cannot select the records anymore. I get panics like

`thread 'main' panicked at 'index 108 out of range for slice of length 8'`

In this case I'm trying to read a newly added timestamp (8 bytes) from a UDT. There is one field preceding the timesamp with a size of 108 bytes.

I noticed this only happening when the UDT is inside a map.

And I wrote a test to debug this, please have a look at the pull request I'm going to create.

**Comment by AlexPikalov** [comment] 2017-12-12 11:23
@dfaust Thanks for reporting the issue. Your PR with steps for reproduction is very helpful.
Will try to make him passing ASAP.

**Comment by AlexPikalov** [comment] 2017-12-12 21:43
@dfaust Here are my quick observations.

I've logged what do we get from 
```rust
let my_map_row: Map = row.get_r_by_name("my_map").expect("my_map");
```

Here's an output:
```
Map { metadata: ColTypeOption { id: Map, value: Some(CMap((ColTypeOption { id: Varchar, value:
 None }, ColTypeOption { id: Udt, value: Some(UdtType(CUdt { ks: CString { string: "cdrs_test" }, 
udt_name: CString { string: "alter_udt_add_udt" }, descriptions: [(CString { string: "my_text" }, 
ColTypeOption { id: Varchar, value: None }), (CString { string: "my_timestamp" }, ColTypeOption { id:
 Timestamp, value: None })] })) }))) }, data: [(CBytes { bytes: Some([49]) }, CBytes { bytes: Some([0,
 0, 0, 7, 109, 121, 95, 116, 101, 120, 116]) })] }
```

As you can see data has two values only:
* array of a single byte 49 which is `1` a key in a map
* `[0, 0, 0, 7, 109, 121, 95, 116, 101, 120, 116]` represents 'my_text' string (with length 7 and following 7 bytes)

Also I've checked non-parsed body - there is no bytes we potentially might missed:
```
Frame { version: Response, flags: [], opcode: Result, stream: 18337, body: [0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 2, 0, 9, 99, 100, 114, 115, 95, 116, 101, 115, 116, 0, 18, 116, 101, 115, 116, 95, 97, 108, 116, 101, 114, 95, 117, 100, 116, 95, 97, 100, 100, 0, 6, 109, 121, 95, 107, 101, 121, 0, 9, 0, 6, 109, 121, 95, 109, 97, 112, 0, 33, 0, 13, 0, 48, 0, 9, 99, 100, 114, 115, 95, 116, 101, 115, 116, 0, 17, 97, 108, 116, 101, 114, 95, 117, 100, 116, 95, 97, 100, 100, 95, 117, 100, 116, 0, 2, 0, 7, 109, 121, 95, 116, 101, 120, 116, 0, 13, 0, 12, 109, 121, 95, 116, 105, 109, 101, 115, 116, 97, 109, 112, 0, 11, 0, 0, 0, 1, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 24, 0, 0, 0, 1, 0, 0, 0, 1, 49, 0, 0, 0, 11, 0, 0, 0, 7, 109, 121, 95, 116, 101, 120, 116], tracing_id: None, warnings: [] }
```

Also I was able to find [following](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L973)

> A UDT value will generally have one value
  for each field of the type it represents, but it is allowed to have less values than
  the type has fields.

Looks like we've faced such behavior.

**Comment by AlexPikalov** [comment] 2017-12-12 21:50
Also I didn't have problems with inserting and querying a map with udts that have string and timestamp fields right away (without type update).

**Comment by dfaust** [comment] 2017-12-12 21:57
Thank you @AlexPikalov for looking into this so quickly.
I don't have the necessary knowledge to be sure what's happening. But it would make sense for C* to always append new fields to the UDT definition (deleting and moving aren't possible, only adding and renaming), while the data stays untouched. During the query C* could append null values for the missing fields or just send the raw data. It seems C* sends the raw data and it's up to the driver to interpret them as null values.

**Comment by dfaust** [comment] 2017-12-12 22:03
This might also be true for table changes, although there seem to be some differences: https://cassandra.apache.org/doc/latest/cql/ddl.html#alter-table

**Comment by AlexPikalov** [comment] 2017-12-13 08:49
@dfaust Thanks. For sure I need to continue investigation what is going on with altering schemas and types.

**Comment by AlexPikalov** [comment] 2017-12-28 13:06
UPD. Fix for this particular issue is merged into master. As for current moment, I'm working on tests for other altering scenarios such as altering table schema.

**Closed** 2018-02-27 08:00 UTC
Labels: bug
